#!/bin/bash

# Check if environment argument is provided
if [ -z "$1" ]; then
    echo "Usage: ./prepare-subgraph.sh [dev|prod]"
    exit 1
fi

ENV=$1
CONFIG_FILE=""

# Set config file based on environment
if [ "$ENV" = "dev" ]; then
    CONFIG_FILE="config/polygon-amoy.json"
elif [ "$ENV" = "prod" ]; then
    CONFIG_FILE="config/matic.json"
elif [ "$ENV" = "local" ]; then
    CONFIG_FILE="config/local.json"
else
    echo "Invalid environment. Use 'dev' or 'prod'"
    exit 1
fi

# Create the warning header
cat > subgraph.yaml << EOL
# ============================================================================
# WARNING: AUTO-GENERATED FILE
# ============================================================================
# This file is automatically generated from template.subgraph.yaml
# DO NOT EDIT THIS FILE DIRECTLY
#
# To regenerate this file, run:
#   bun run prepare:env
# ============================================================================

EOL

# Append the processed template
bun mustache ${CONFIG_FILE} template.subgraph.yaml >> subgraph.yaml

echo "✅ Generated subgraph.yaml for ${ENV} environment" 